{% set version = '3.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-callr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/callr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/callr/callr_{{ version }}.tar.gz
  sha256: cc87552481d6a863bc5045e1185f7a7a001bd1f29eb558ca0fac48423cddcb1e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-processx >=3.4.0
  run:
    - r-base
    - r-r6
    - r-processx >=3.4.0

test:
  commands:
    - $R -e "library('callr')"           # [not win]
    - "\"%R%\" -e \"library('callr')\""  # [win]

about:
  home: https://github.com/r-lib/callr#readme
  license: MIT
  summary: It is sometimes useful to perform a computation in a separate R process, without affecting
    the current R process at all. This packages does exactly that.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: callr
# Title: Call R from R
# Version: 3.3.0
# Authors@R: c( person("Gabor", "Csardi", role = c("aut", "cre", "cph"), email = "csardi.gabor@gmail.com", comment = c(ORCID = "0000-0001-7098-9676")), person("Winston", "Chang", role = "aut"), person("RStudio", role = c("cph", "fnd")), person("Mango Solutions", role  = c("cph", "fnd")))
# Description: It is sometimes useful to perform a computation in a separate R process, without affecting the current R process at all. This packages does exactly that.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/r-lib/callr#readme
# BugReports: https://github.com/r-lib/callr/issues
# RoxygenNote: 6.1.1
# Imports: processx (>= 3.4.0), R6, utils
# Suggests: cliapp, covr, crayon, knitr, pingr, ps, rmarkdown, rprojroot, spelling, testthat, tibble, withr
# Encoding: UTF-8
# VignetteBuilder: knitr
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-07-04 09:18:46 UTC; gaborcsardi
# Author: Gabor Csardi [aut, cre, cph] (<https://orcid.org/0000-0001-7098-9676>), Winston Chang [aut], RStudio [cph, fnd], Mango Solutions [cph, fnd]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-04 09:50:09 UTC
