travis:
  secure:
    BINSTAR_TOKEN: lOA9ZYYra/QmLw9+pAf3pkEnD6lXP/K7yhrwvT4AVNn8/yl/NQVpk+ptiY2anM26U8HD9YftF2+N56pd55TY27TSQXO6HEHmDY1HaD9Am2isvQZvLzGV3RvfUwBFt8t3uryOyHl1P7d7zlPLJu4nFQ/kd/Wkxwn3zAxlYR4hkbx5P8AJSBN4BdK6ofWyU1Z3IQb4AnYrBE8v+EY+eh3rs9w6g2WLgweTBrv8bSEodAh31em7R1q2LuTEIoVAetMYQOX31cmyCR9Yumkfg3kL6HcZRr5exc6rduw4cwuyJgBvGwj9zKwSpKzlbDD5AGGbC0oknPt/iXPNZYKPvRMJ1VBQJKxDO4gxnlnIyK9CCTlDDSUX1pazg2uSn+FDmEnh1ZUofXRGz4x4IMNc3Dz6zXeZEkhTHGgm+11aPc8njLRnJkYKwoAyzohQmHLqoRr8wWV0pflCcvMGbWqhIZhm32QsQZT1JsfErFnUrlJK0mhdIf3wZZ0Nsp8R/gELBTmzml4MoCG45C/IeUR8w6QMT2iyyGHGyCva4Hwe7NL9qQr0DBFdpojVPaxBXbAKkfow532S7BzA953Tyu2DcJV3p38f3qtZyYKlFNHM0IdYDZNowTI0y2XIRjyZ4J5XCJgAAhGTbt1ZydyKax/9mpfyrgEWxFr3hOSASj7btFTGkiI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
