travis:
  secure:
    BINSTAR_TOKEN: Po/ImEJYOil/tKaMGoaw9as8pzWDyQdvn/YKukgsIi5P/OL9hApI8sFYYkOpeYR8C64+JEpZyr3G/NoAuXTaMsaOQbam8AwJjG0N46PK9jEQWbCgpzfk/6gHADcKie31KdkpWvhSiX0QGHKBF4H3H3yZrtS8sXtfUAM7aZPDYtTPpi/OJBCPE1mpOkH0l2n7Qza7mUGVZZhDOd0yeQGXjWWPnLYVWHOrUSvv0nYr12+3u8l/PCwhOLyHfR0678uR51AJzckt5pdiAKdAdex4pKk02bL78vdgXugZqC8Zs6HRPYOEQMyfREor/mnw9DNKf/7mhLjBXTUgC+9DFg/musswIHMIfKVtO3bqBRqZaOAQQD2hcxzJ+yqukZTcqZf0IDncxQR4zBQv4mq1McA/7xMkW/q7AWe284bPfwuqkIe1IWfQv8kc49aUvcSZml49SN4J9cSircJpHExMnK7qzpRJ0LGinr3GjklO40crrdlGVAJpSGCHjRYmYaPXYTyTAXC4NFgj2ChxFBQOQYvAb6ZbfmtiGOPZi9K9IRM+usHTC8wOBI5u82zf+wKM3xay9W0Bml5GtCK1lrkwAQJIqBaX/HFaMNfzGfLrgkVHBo+5X8gPg2S5Gffe6VyXkjrBiD5/uxZXKWA/pKircnvtlzYz8fgnx0ROjaVlYC3ysDk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
