travis:
  secure:
    BINSTAR_TOKEN: oDIB0SmiR5j25jghz61h7p4p7evtwEq/ShmwP5FhA3B1YUD5Rx5J/pyss1poQ8QPNlijwFxhDW3bZStLLv4rJxdKl4/3yYHQKj3bRLS5Oqo40XSn3YqGy5mI5KWPEYxV1yBry9pu/ebPH8sjVhKma9a8/9InftcXj9kDLAgIKuOE8mVjRszhOgws7i6TRNDYx5BTQDQs9i/UHh++skb6ehU1n8ZaLWBJuOtP5Ry+24364Hh5rsIAveeG4KXA07A8qiy7y2yQPs1lZNiTcdU94IuJnWEB2ucSLlxQVekdZ0V7Kj7dTPmucvHAFn8ko2m3Kh/rhwi60eCG3mywG+Qt/kUdLYKncR6m4+XElSHxBK6KmFTjAkTnmxVvb7p+t4JIvoFjCsmWCImYxGclMJQM+5AGBe74dTp6L/4aZLAmXOcJ2Jqa28f7nMoIrsQi+xYSLBjhCbJiJ8f1tghXQqa5mrbJWQ20KFcd8U/hGBniCayDMC2OKuN5wpCD7ykV6bKp1DM55duPOBLT+fVvp31FvavRY1hZeQXZxPXKNXKDAgtW7jfqL0llCWsihKbTKQH7CorN7kEdl7f9ZqbGcStzdlmw7OYi6hUGqN6iaOlJTRqsw0YAVs27fVpbgXuhA0lMC50C+E2X6Qul4/BRoiF5sHXI/f8Lp5bmpBB9XVPzV4E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
